name: "go-linter"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"
      - go.mod
      - go.sum
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - "**.go"
      - go.mod
      - go.sum

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://proxy.golang.org/,direct
      GOPRIVATE: ""
      GONOPROXY: ""
      GONOSUMDB: github.com/github/*
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - uses: actions/checkout@v4
      - name: Lint
        # This also does checkout, setup-go, and proxy setup.
        uses: github/go-linter@v1.2.1
        with:
          strict: true
          go-version: ${{ vars.GOVERSION }}
          goproxy-token: ${{secrets.GOPROXY_TOKEN}}
