name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: true

permissions:
  contents: write
  id-token: write
  attestations: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@561b19deda1228a0edf856c3325df87416f8c9bd
        with:
          go_version_file: go.mod
          release_tag: ${{ github.event.inputs.release_tag || '' }}
          generate_attestations: true
          release_android: true
          android_sdk_version: 34
